### PR TITLE
Added a BOOL to let user choose a slimmer cell width, keeping base formula for default width.

### PR DESCRIPTION
**Pull request by klauslanza**
Refactored with no API changes.

### CODE REVIEW

**Comment by benguild** [comment]
I can take a look at this later. Did you update the README to document the additional constructor(s)? Also, any code cleanup is appreciated.

**Comment by klauslanza** [comment]
I've already added the main method to the README, now I'm adding also the multiple constructor for completeness.
I've done a light cleanup on the .m file, hope it's ok with your style.

Thanks for your time and valuable project!
Cheers

**Comment by klauslanza** [comment]
Ok, updated the README!

**Comment by klauslanza** [comment]
Is there some other problems with this PR? Just let me know, I'll try to fix ASAP.

Thanks for your time

**Comment by benguild** [comment]
Merged, sorry for the delay. I'll bump the pod version shortly.

**Comment by klauslanza** [comment]
No worries, I was just checking out it was ok!
Thanks and have a great day.

**Pull request merged**
