### PR TITLE
compatible with multi line text

### PR DESCRIPTION
**Pull request by bestwnh**
support multi line text

### CODE REVIEW

**Comment by benguild** [comment]
Do you have a screenshot of what this does?

**Comment by bestwnh** [comment]
This is the unsupported(original) result.
unsupport

This is the supported result.
support

**Comment by benguild** [comment]
Very interesting! I'll do code review and confirm when I have the chance. Thanks!

**Comment by bestwnh** [comment]
Oh, never found a `enumerateLinesUsingBlock ` method. Much better!

**Pull request merged**
