### PR TITLE
Center image vertically if no title is provided

### PR DESCRIPTION
**Pull request by tomaskraina**

### CODE REVIEW

**Comment by benguild** [comment]
Thanks, will check it out soon.

**Comment by benguild** [comment]
@tomaskraina I merged the PR. Would you be able to clone this and run `pod trunk push` to update the trunk?

I can't do it because of an issue with Cocoa Pods and Xcode 8. :( https://github.com/CocoaPods/CocoaPods/issues/5661

**Comment by tomaskraina** [comment]
It seems that you need to add me as an owner of the pod:

```
[!] You (tomas.kraina@gmail.com) are not allowed to push new versions for this pod. The owners of this pod are ben@benguild.com.
```

You can do that by running: `pod trunk add-owner BGTableViewRowActionWithImage tomas.kraina@gmail.com`

**Comment by benguild** [comment]
Done, let me know if it worked so that I can close this out :)

**Comment by tomaskraina** [comment]
Pushed to Cocoapods. You can close this now. Thanks :)

**Comment by benguild** [comment]
Thanks for your help!

**Comment by tomaskraina** [comment]
You're welcome :)

Btw. How did you come up with such a "hack" for showing an image on `UITableViewRowAction`? I mean, it's pretty elegant actually and I would never think of drawing the image in `UITableViewRowAction`'s initializer. I still don't understand how it can work... :)

**Comment by tomaskraina** [comment]
No, wait. I just noticed this row:

```
[rowAction setBackgroundColor:[UIColor colorWithPatternImage:UIGraphicsGetImageFromCurrentImageContext()]];
```

Yeah, that explains everything :)

**Comment by benguild** [comment]
:)

**Pull request merged**
