### PR TITLE
vertical center image and text.

### PR DESCRIPTION
**Pull request by bestwnh**
support vertical center image and text

### CODE REVIEW

**Comment by benguild** [comment]
Thanks for contributing your two commits. I cleaned up the other one and merged that. Can you tell us a little bit about this one?

The formulas are a little tricky for aligning the image, and we can't make any drastic changes as it might break support for current applications.

**Comment by bestwnh** [comment]
At first, let's make it clean. The code change only effect the situation with text. Nothing change for only image.
screen shot 2017-01-21 at 18 17 29

There are two parts of change, let's focus the second(simple) one.
`(frameGuess.height/2.0f)-imageInsetVertical+[image size].height+margin_vertical_betweenTextAndImage`
It's the y position for the text. From line 94 we can found out the `(frameGuess.height/2.0f)-imageInsetVertical` is the y position of the image, so image.y + `[image size].height+margin_vertical_betweenTextAndImage` is the text.y. I think it's pretty clear, right?

Then to the first part
`imageInsetVertical=([image size].height+margin_vertical_betweenTextAndImage+drawnTextSize.height)/2.0f;`
I make a graph to make it clear.
screen shot 2017-01-21 at 19 20 56
I change the value of `imageInsetVertical`, the `imageInsetVertical` is the inset between image.y and superview.middle(BTW, I don't think `imageInsetVertical` is a good concept, too complex, but I don't want to change too many codes).
To make the text and image vertical center, it just mean the `imageInsetVertical` is 1/2 of the height of the dashed line part.

**Comment by benguild** [comment]
Can you post screenshots of the before/after different in effect?

**Comment by bestwnh** [comment]
before
screen shot 2017-01-22 at 13 55 16
screen shot 2017-01-22 at 13 57 29

after
screen shot 2017-01-22 at 13 56 20
screen shot 2017-01-22 at 13 58 31

The old version is not compatible  with multi line text.

**Comment by benguild** [comment]
Hmm, OK. I think the vertical alignment issue I mentioned in #12 was from something else, but this seems fine, and so I've created #18.

**Pull request merged**
